spring:
  application:
    name:spring-boot-demo
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
  datasource:
    staff:
      url: jdbc:mysql://localhost:3307/example
      username: user
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: staff-master-cp
        maximum-pool-size: 20
        connection-init-sql: "SET NAMES 'utf8mb4'"
        max-lifetime: 60000
    product:
      url: jdbc:mysql://localhost:3308/product
      username: product_user
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: staff-master-cp
        maximum-pool-size: 20
        connection-init-sql: "SET NAMES 'utf8mb4'"
        max-lifetime: 60000

