spring:
  application:
    name: spring-boot-demo
  cassandra:
    contact-points: 127.0.0.1
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: example
    schema-action: CREATE_IF_NOT_EXISTS

datastax-java-driver:
  basic:
    contact-points: 127.0.0.1:9042
