version: '3.8'

services:
  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla
    ports:
      - "9042:9042"
    volumes:
      - scylla-data:/var/lib/scylla
    command:
      - "--developer-mode"
      - "1"
      - "--smp"
      - "1"
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  scylla-data: